# Base configs
baseurl: "https://senyiyang.github.io"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Senyi Yang"
subtitle: "See the world through my eyes!"
author: "Senyi Yang"
header:
 title: "Photography"
 subtitle: "by Senyi Yang"
footer:
 name: "I am Senyi. "
 bio: "This website serves as a way to showcase my favorite pieces, particularly automotive content."
 github: "You can access the full portfolio and complete shoots here at"
web_design: "Senyi Yang"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  #twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/senyi.jpg"
  #dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/senyi-yang-343106268"
  #github: "https://www.github.com/rampatra"
